server:
  port: 9031
spring:
  application:
    name: hystrix-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/,http://localhost:9003/eureka/
  instance:
    prefer-ip-address: true

turbine:
  # 要监控的微服务列表，多个用,分隔
  appConfig: order-service
  clusterNameExpression: "'default'"
