spring:
  application:
    name: eureka-server
---
spring:
  profiles: eureka1
server:
  port: 9000
eureka:
  instance:
    hostname: eureka1
  client:
#    register-with-eureka: false #是否将自己注册到注册中心
#    fetch-registry: false # 是否从eureka中获取注册信息
    service-url:
      defaultZone: http://eureka1:9003/eureka/
  server:
    enable-self-preservation: false #关闭自我保护
    eviction-interval-timer-in-ms: 4000 #剔除服务间隔
---
spring:
  profiles: eureka2
server:
  port: 9003
eureka:
  instance:
    hostname: eureka2
  client:
#    register-with-eureka: false #是否将自己注册到注册中心
#    fetch-registry: false # 是否从eureka中获取注册信息
    service-url:
      defaultZone: http://eureka2:9000/eureka/
  server:
    enable-self-preservation: false #关闭自我保护
    eviction-interval-timer-in-ms: 4000 #剔除服务间隔